name: Arm Virtual Hardware hello_vsi example
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '30 22 * * 0'


permissions:
  actions: read
  security-events: write


jobs:
   CI_test_run:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Setup Python 3.10
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
  

