name: Arm Virtual Hardware hello_vsi example
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '30 22 * * 0'


permissions:
  actions: read
  security-events: write


jobs:
   CI_test_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
  
      - name: Install system packages
          run: |
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt-get install libpython3.9 libtinfo5

      - name: Activate vcpkg
        uses: ARM-software/cmsis-actions/vcpkg@v1

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Build context Corstone_300_AC6
          run: |
            echo "Building Arm Virtual Hardware hello_vsi example by using the context Corstone_300..."
            cbuild hello_vsi.csolution.yml --update-rte --packs --context hello_vsi.event+Corstone_300 --toolchain AC6

      - name: Execute context Corstone_300_AC6
          run: |
            echo "Running the Corstone_300 context build with AC6"
            FVP_Corstone_SSE-300 -a ./out/hello_vsi/Corstone_300/event/hello_vsi.axf -C mps3_board.v_path=./source/VSI/data_sensor/python/ --simlimit 60 --stat | tee Corstone_300_AC6.avh.log
            echo "Checking output..."
            test "$(grep "FAIL: " Corstone_300_AC6.avh.log | wc -l)" -eq 0