name: Arm Virtual Hardware hello_vsi example
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '30 22 * * 0'

jobs:
  CI_test_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Activate vcpkg
        uses: ARM-software/cmsis-actions/vcpkg@v1

      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Build context Corstone_300_AC6
        run: |
            echo "Building Arm Virtual Hardware hello_vsi example by using the context Corstone_300..."            
            cbuild hello_vsi.csolution.yml --update-rte --packs --context hello_vsi.event+Corstone_300 --toolchain AC6
        working-directory: ./hello_vsi

      - name: Execute context Corstone_300_AC6
        run: |
            echo "Running the Corstone_300 context build with AC6"
            FVP_Corstone_SSE-300 -a ./out/hello_vsi/Corstone_300/event/hello_vsi.axf -C mps3_board.v_path=./source/VSI/data_sensor/python/ -C mps3_board.visualisation.disable-visualisation=1 --simlimit 60 --stat | tee Corstone_300_AC6.avh.log
            echo "Checking output..."
            test "$(grep "FAIL: " Corstone_300_AC6.avh.log | wc -l)" -eq 0
        working-directory: ./hello_vsi

      - name: Upload report for context Corstone_300_AC6
        uses: actions/upload-artifact@v4
        with:
          name: Corstone_300_AC6.avh.log
          path: ./
          working-directory: ./hello_vsi

      - name: Build context Corstone_310_AC6
        run: |
            echo "Building Arm Virtual Hardware hello_vsi example by using the context Corstone_310..."
            cbuild hello_vsi.csolution.yml --update-rte --packs --context hello_vsi.event+Corstone_310 --toolchain AC6
        working-directory: ./hello_vsi

      - name: Execute context Corstone_310_AC6
        run: |
            echo "Running the Corstone_310 context build with AC6"
            FVP_Corstone_SSE-310 -a ./out/hello_vsi/Corstone_310/event/hello_vsi.axf -C mps3_board.v_path=./source/VSI/data_sensor/python/ -C mps3_board.visualisation.disable-visualisation=1 --simlimit 60 --stat | tee Corstone_310_AC6.avh.log
            echo "Checking output..."
            test "$(grep "FAIL: " Corstone_310_AC6.avh.log | wc -l)" -eq 0
        working-directory: ./hello_vsi

      - name: Build context Corstone_315_AC6
        run: |
            echo "Building Arm Virtual Hardware hello_vsi example by using the context Corstone_315..."
            cbuild hello_vsi.csolution.yml --update-rte --packs --context hello_vsi.event+Corstone_315 --toolchain AC6
        working-directory: ./hello_vsi

      - name: Execute context Corstone_315_AC6
        run: |
            echo "Running the Corstone_315 context build with AC6"
            FVP_Corstone_SSE-315 -a ./out/hello_vsi/Corstone_315/event/hello_vsi.axf -C mps4_board.v_path=./source/VSI/data_sensor/python/ -C mps4_board.visualisation.disable-visualisation=1  -C vis_hdlcd.disable_visualisation=1 --simlimit 60 --stat | tee Corstone_315_AC6.avh.log
            echo "Checking output..."
            test "$(grep "FAIL: " Corstone_315_AC6.avh.log | wc -l)" -eq 0
        working-directory: ./hello_vsi